### ISSUE TITLE
not works for this link

### ISSUE THREAD

**Issue by HaveF** [mayankjuneja/vl-download#1]
http://videolectures.net/mackay_course_02/

I used your script before, but when I use it today, it errors:

```
$ vl-download -u http://videolectures.net/mackay_course_02/ -o test.flv
Traceback (most recent call last):
  File "c:/Prog/usr_bin/vl-download", line 77, in <module>
    rtmp_section = html_page.findAll('script')[5].contents[0]
IndexError: list index out of range
```

Thanks!

**Comment by mayankjuneja** [comment]
Thanks for pointing it out, looks like the streaming player has changed. It now supports multiple formats/resolutions. I have written a fix for this and updated the master.

**Comment by HaveF** [comment]
still not works, 403 error

```
$ vl-download -u http://videolectures.net/mackay_course_02/
Downloading video:  Lecture_2:_Entropy_and_Data_Compression_(I):__Introduction_to_Compression,_Infor
mation_Theory_and_Entropy-
Traceback (most recent call last):
  File "c:/Prog/usr_bin/vl-download", line 117, in <module>
    u = urllib2.urlopen(req)
  File "c:\Anaconda\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "c:\Anaconda\lib\urllib2.py", line 406, in open
    response = meth(req, response)
  File "c:\Anaconda\lib\urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Anaconda\lib\urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "c:\Anaconda\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "c:\Anaconda\lib\urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

BTW, if the file name contains `\/:*?“<>|`, it may has problems.

Thanks for your reply :+1:  I like your scripts!

**Comment by mayankjuneja** [comment]
Thanks for the appreciation! Good to see someone actually using it.

I see the issue here, though it did work for some other lectures. I will take a look and fix it.
